#!/bin/bash

# ZFS Root Installation Scripts - NixOS Configuration (v0.1)
# Copyright (C) 2025 Michael C. Tinsay
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Edit these variables before running the installation scripts
#
# ⚠️  AI-GENERATED CODE DISCLAIMER ⚠️
# This configuration file was entirely generated by AI without direct human editing.
# No comprehensive human testing or code review has been performed.
# Thoroughly review all settings and test in isolated environments before use.
# Use at your own risk - AI-generated code may contain subtle bugs.

# Partitioning mode: "auto" or "manual"
# auto: Script will partition DISK automatically (destroys all data)
# manual: Use existing partitions specified below
PARTITION_MODE="manual"

# Auto partitioning configuration (used when PARTITION_MODE="auto")
DISK="/dev/sda"  # WARNING: All data on this disk will be destroyed!
EFI_SIZE="1G"
BOOT_SIZE="4G"

# Manual partitioning configuration (used when PARTITION_MODE="manual")
# Specify existing partitions to use
EFI_PARTITION=""        # e.g., "/dev/sda1" - EFI System Partition (required)
# Important: EFI and Boot partitions must be compatible for GRUB installation
# Options:
#   1. Both on same drive: EFI=/dev/sda1, BOOT=/dev/sda2
#   2. RAID 1 boot with one device on EFI drive: EFI=/dev/sda1, BOOT=/dev/md0 (where md0 includes /dev/sda3)
BOOT_PARTITION=""       # e.g., "/dev/sda2" or "/dev/md0" - Boot partition (ext4 or RAID 1, required)
ROOT_PARTITION=""       # e.g., "/dev/sda3" - Root pool partition (required)
SWAP_PARTITION=""       # e.g., "/dev/sda4" - Swap partition (optional, leave empty to disable swap)

# System configuration
HOSTNAME="nixos-zfsroot"

# User Configuration
# Format: "username:groups:password:description" where groups are comma-separated
# Leave groups empty for no additional groups beyond the default user group
# Leave password empty to set manually during installation
# Common groups:
#   - wheel: Administrative privileges (sudo equivalent)
#   - networkmanager: Network management
#   - audio: Audio device access
#   - video: Video device access
#   - docker: Docker container management
#   - libvirtd: Virtualization management
# 
# Examples:
#   "admin:wheel:secretpass:System Administrator" - Admin user with wheel privileges
#   "user:audio,video,wheel::Regular User" - User with multiple groups, password set manually
#   "guest:::Guest User" - Guest user with no additional groups
USERS=(
    "localadmin:wheel,networkmanager,audio,video::Local Administrator"
    # "admin:wheel:adminpass123:System Administrator"
    # "guest:::Guest User"
)

# Installation configuration
NIXOS_CHANNEL="nixos-25.05"    # NixOS channel (nixos-25.05, nixos-unstable, etc.)
INSTALL_ROOT="/mnt"            # Root mountpoint for installation
AUTO_RUN_STAGE2="true"         # Automatically run stage2 after stage1 completes
DEBUG="false"                  # Set to "true" to pause before executing nixos-install for debugging

# ZFS configuration
POOL_NAME="zpool"
ROOT_DATASET_NAME="NixOS"      # Top-level root dataset name (e.g., "ROOT", "SYSTEM", "OS")
                               # All datasets will be created under this: rpool/NixOS/home, rpool/NixOS/var, etc.

# ZFS pool reuse options
# Set to "true" to reuse existing ZFS pools instead of creating new ones
REUSE_ROOT_POOL="true"         # Reuse existing root pool (must match POOL_NAME)

# When reusing pools, specify the dataset to use as root filesystem
# Leave empty to create new $ROOT_DATASET_NAME dataset as root
EXISTING_ROOT_DATASET=$POOL_NAME/$ROOT_DATASET_NAME    # e.g., "zpool/NixOS" - existing dataset to reuse

# Network interface (adjust if needed)
NETWORK_INTERFACE="enp1s0"

# Timezone (change as needed)
TIMEZONE="Asia/Manila"

# Locale settings
LOCALE="en_PH.UTF-8"

# Swap partition size (set to 0 or empty to disable swap entirely)
# In auto mode: Creates a dedicated swap partition with this size
# In manual mode: Use SWAP_PARTITION to specify existing swap partition
SWAP_SIZE="4G"

# ZFS Dataset Configuration
# Format: "dataset_name:mountpoint:options" (options are optional)
# All datasets will be created under $POOL_NAME/$ROOT_DATASET_NAME/
# Leave empty entries or comment out lines to skip specific datasets
#
# NOTE: All datasets are automatically created with mountpoint=legacy
# Any mountpoint= options in the configuration will be ignored

ZFS_DATASETS=(
    # Home datasets
    "home:/home:"
    "home/root:/root:"
    
    # Var datasets (organized by hierarchy)
    "var:/var:"
    "var/cache:/var/cache:"
    "var/lib:/var/lib:"
    "var/log:/var/log:"
    "var/tmp:/var/tmp:"
    
    # Nix store datasets
    "nix:/nix:"
    "nix/store:/nix/store:"
    "nix/var:/nix/var:"
    
    # Opt datasets
    "opt:/opt:"
    "srv:/srv:"
    "tmp:/tmp:"
)

# NixOS Configuration
# Additional packages to include in the system configuration
SYSTEM_PACKAGES=(
    "vim"
    "git"
    "curl"
    "wget"
    "htop"
    "tree"
    "firefox"
    "zfs"
)

# Services to enable
SYSTEM_SERVICES=(
    "openssh"
    "networkmanager"
    "zfs.autoScrub"
    "zfs.autoSnapshot"
)

# Desktop Environment (leave empty for minimal installation)
# Options: "gnome", "kde", "xfce", "i3", "sway", ""
DESKTOP_ENVIRONMENT=""

# Boot loader configuration
BOOTLOADER_TIMEOUT="5"         # GRUB timeout in seconds
ENABLE_MEMTEST="true"          # Enable memtest86+ in GRUB menu

# Hardware configuration
ENABLE_MICROCODE_UPDATES="true"  # Enable CPU microcode updates
ENABLE_FIRMWARE_UPDATES="true"   # Enable firmware updates

# Color Configuration for Script Output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color