#!/bin/bash

# ZFS Root Installation Scripts - Configuration (v0.1)
# Copyright (C) 2025 Michael C. Tinsay
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Edit these variables before running the installation scripts
#
# ⚠️  AI-GENERATED CODE DISCLAIMER ⚠️
# This configuration file was entirely generated by AI without direct human editing.
# No comprehensive human testing or code review has been performed.
# Thoroughly review all settings and test in isolated environments before use.
# Use at your own risk - AI-generated code may contain subtle bugs.

# Partitioning mode: "auto" or "manual"
# auto: Script will partition DISK automatically (destroys all data)
# manual: Use existing partitions specified below
PARTITION_MODE="auto"

# Auto partitioning configuration (used when PARTITION_MODE="auto")
DISK="/dev/sda"  # WARNING: All data on this disk will be destroyed!
EFI_SIZE="1G"
BOOT_SIZE="4G"

# Manual partitioning configuration (used when PARTITION_MODE="manual")
# Specify existing partitions to use
EFI_PARTITION=""        # e.g., "/dev/sda1" - EFI System Partition (required)
# Important: EFI and Boot partitions must be on the same drive for GRUB installation
# This is required for proper bootloader installation and UEFI compatibility
BOOT_PARTITION=""       # e.g., "/dev/sda2" - Boot partition (ext4, required)
ROOT_PARTITION=""       # e.g., "/dev/sda3" - Root pool partition (required)
SWAP_PARTITION=""       # e.g., "/dev/sda4" - Swap partition (optional, leave empty to use ZFS swap)

# System configuration
HOSTNAME="multiboot-zfsroot"

# User Configuration
# Format: "username:groups:password" where groups are comma-separated
# Leave groups empty for no additional groups beyond the default user group
# Leave password empty to set manually during installation
# Common groups:
#   - sudo: Administrative privileges
#   - adm: System monitoring logs
#   - cdrom: CD-ROM access
#   - dip: Dial-up networking
#   - lpadmin: Printer administration
#   - lxd: LXD container management
#   - plugdev: Pluggable device access
#   - sambashare: Samba file sharing
# 
# Examples:
#   "admin:sudo:secretpass" - Admin user with sudo privileges and preset password
#   "user:adm,cdrom,sudo:" - User with multiple groups, password set manually
#   "guest::" - Guest user with no additional groups, password set manually
USERS=(
    "localadmin:adm,cdrom,dip,lpadmin,lxd,plugdev,sambashare,sudo:Golden Soda Pop!"
    # "admin:sudo:adminpass123"
    # "guest::"
)

# Installation configuration
DEBOOTSTRAP_SUITE="noble"   # Ubuntu release codename (noble=24.04, jammy=22.04, focal=20.04, etc.)
INSTALL_ROOT="/mnt"         # Root mountpoint for installation
AUTO_RUN_STAGE2="true"      # Automatically run stage2 after stage1 completes
DEBUG="false"               # Set to "true" to pause before executing chroot for debugging
CACHE_DIR="/var/cache/apt/archives"  # Cache directory for debootstrap and package downloads
INSTALL_SSH="true"          # Install OpenSSH server (can be overridden with --ssh/--nossh)

# ZFS configuration
POOL_NAME="zpool"
ROOT_DATASET_NAME="mint"    # Top-level root dataset name (e.g., "ROOT", "SYSTEM", "OS")
                           # All datasets will be created under this: rpool/ROOT/home, rpool/ROOT/var, etc.

# ZFS pool reuse options
# Set to "true" to reuse existing ZFS pools instead of creating new ones
REUSE_ROOT_POOL="true"     # Reuse existing root pool (must match POOL_NAME)

# When reusing pools, specify the dataset to use as root filesystem
# Leave empty to create new $ROOT_DATASET_NAME dataset as root
EXISTING_ROOT_DATASET=$POOL_NAME/$ROOT_DATASET_NAME    # e.g., "zpool/mint" - existing dataset to reuse

# Network interface (adjust if needed)
NETWORK_INTERFACE="enp1s0"

# Timezone (change as needed)
TIMEZONE="Asia/Manila"

# Locale settings
LOCALE="en_PH.UTF-8"

# Swap partition size (set to 0 or empty to disable swap entirely)
# In auto mode: Creates a dedicated swap partition with this size
# In manual mode: Use SWAP_PARTITION to specify existing swap partition
SWAP_SIZE="4G"

# ZFS Mount Configuration
# How to mount ZFS datasets at boot: "zfs" or "fstab"
# zfs: Use ZFS native mounting (zfs mount -a)
# fstab: Use /etc/fstab entries for mounting
ZFS_MOUNT_METHOD="fstab"

# ZFS Dataset Configuration
# Format: "dataset_name:mountpoint:options" (options are optional)
# All datasets will be created under $POOL_NAME/$ROOT_DATASET_NAME/
# Leave empty entries or comment out lines to skip specific datasets
#
# NOTE: All datasets are automatically created with mountpoint=legacy
# Any mountpoint= options in the configuration will be ignored
#
# The following datasets are commented out by default for a minimal installation.
# Uncomment any datasets you want to create at your discretion.

ZFS_DATASETS=(
    # Home datasets
    "home:/home:"
    "home/root:/root:"
    
    # Var datasets (organized by hierarchy) - uncomment as needed
    # "var:/var:"
    
    # Level 1: Direct /var subdirectories (alphabetical) - uncomment as needed
    # "var/cache:/var/cache:"
    # "var/games:/var/games:"
    # "var/lib:/var/lib:"
    # "var/log:/var/log:"
    # "var/mail:/var/mail:"
    # "var/snap:/var/snap:"
    # "var/spool:/var/spool:"
    # "var/tmp:/var/tmp:"
    # "var/www:/var/www:"
    
    # Level 2: /var/lib subdirectories (alphabetical) - uncomment as needed
    # "var/lib/AccountsService:/var/lib/AccountsService:"
    # "var/lib/apt:/var/lib/apt:"
    # "var/lib/dpkg:/var/lib/dpkg:"
    # "var/lib/NetworkManager:/var/lib/NetworkManager:"
    # "var/lib/nfs:/var/lib/nfs:"
    
    # Usr datasets - uncomment as needed
    # "usr:/usr:"
    # "usr/local:/usr/local:"
    
    # Opt datasets - uncomment as needed
    # "opt:/opt:"
    # "srv:/srv:"
)

# Package Configuration
# Additional packages to install during stage2
ADDITIONAL_PACKAGES=(
    # "ubuntu-minimal"
    # "ubuntu-standard"
    # "ubuntu-desktop"
    # "hollywood"
    # "sanoid"
)

# Color Configuration for Script Output
# Recommended combinations:
# - Default: RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
# - High contrast: RED='\033[1;31m' GREEN='\033[1;32m' YELLOW='\033[1;33m'
# - Subtle: RED='\033[0;91m' GREEN='\033[0;92m' YELLOW='\033[0;93m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color
